#!/usr/bin/env bash

TIDEL_PATH="$HOME/.tidel"
TIDEL_SCRIPTS_PATH="$TIDEL_PATH/scripts"

function info() {
  echo -e "\033[0;32mInfo: ${1}\033[0;39m"
}

function warn_and_continue() {
  echo -e "\033[0;33mWarn: ${1}\033[0;39m"
}

function error_and_exit() {
  echo -e "\033[0;31mError: ${1}\033[0;39m" >&2
  exit 1
}
