#!/usr/bin/env bash

TIDEL_PATH="$HOME/.tidel"
TIDEL_SCRIPTS_PATH="$TIDEL_PATH/scripts"

function info() {
  echo -e "\033[0;32m[INFO] ${1}\033[0;39m"
}

function error_and_exit() {
  echo -e "tidel: $(basename ${0}): \033[0;31m[ERROR] ${1}\033[0;39m" >&2
  exit 1
}
