#!/usr/bin/env bash
source $TIDEL_ROOT/libexec/helpers

[ -d $TIDEL_PATH ] && warn_and_continue "Tidel is already initialized"

mkdir -p $TIDEL_PATH
info "$TIDEL_PATH successfully created"
mkdir -p $TIDEL_SCRIPTS_PATH
info "$TIDEL_SCRIPTS_PATH successfully created"
