#!/usr/bin/env bash
source $TIDEL_ROOT/libexec/helpers

if [ -d $TIDEL_PATH ] && [ -d $TIDEL_SCRIPTS_PATH ]; then
  warn_and_continue "Tidel is already initialized"
fi

if [ ! -d $TIDEL_PATH ]; then
  mkdir -p $TIDEL_PATH
  info "$TIDEL_PATH successfully created"
fi

if [ ! -d $TIDEL_SCRIPTS_PATH ]; then
  mkdir -p $TIDEL_SCRIPTS_PATH
  info "$TIDEL_SCRIPTS_PATH successfully created"
fi
